[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.arguments]
NODE_VERSION = "18"

[[services]]
name = "web"
run = "npm start"